### ISSUE TITLE
How to Change the Output Path for Generated Files in Squadron Builder?

### ISSUE THREAD

**Issue by yesilcimenahmet** [d-markey/squadron#55]
I am trying to use Squadron with source_gen to generate files in a custom output directory, but the generated files are not being placed in the desired location. Specifically, I want the generated files to be placed under a generated subdirectory (e.g., lib/squadron/generated/), but they are always created in the same directory as the source files.

1) Configuring build.yaml:
I updated the build.yaml file with the following configuration:

```
targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/squadron/image_converter/{{}}.dart':
              - 'lib/squadron/generated/{{}}.activator.g.dart'
              - 'lib/squadron/generated/{{}}.vm.g.dart'
              - 'lib/squadron/generated/{{}}.worker.g.dart'
```

Despite this, the generated files (.worker.g.dart, .vm.g.dart, .activator.g.dart) still appear in the lib/squadron/image_converter/ directory instead of lib/squadron/generated/.

2) Manually Testing a Single File Path:
I simplified the configuration to target a single file directly, like this:

```
targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/squadron/image_converter/converter.dart':
              - 'lib/squadron/generated/converter.activator.g.dart'
              - 'lib/squadron/generated/converter.vm.g.dart'
              - 'lib/squadron/generated/converter.worker.g.dart'
```

However, even with this specific setup, the generated files are still placed in the same source directory.

3) Cleaning and Rebuilding the Project:
I ensured to clean the project and build_runner cache before each attempt:

```
flutter clean
dart run build_runner clean
dart run build_runner build
```

4) Checking Dependencies:
I updated all relevant dependencies in pubspec.yaml to ensure compatibility:

dependencies:
  squadron: ^6.1.3

```
dev_dependencies:
  build_runner: ^2.4.13
  source_gen: ^1.5.0
  squadron_builder: ^6.1.1
```

**Expected Behavior**
I expect the generated files (.worker.g.dart, .vm.g.dart, .activator.g.dart) to be placed in the directory lib/squadron/generated/ instead of the same directory as the source files (lib/squadron/image_converter/).

**Actual Behavior**
The generated files are always created in the same directory as the source files, regardless of the build.yaml configuration.

Is it possible to specify a custom output directory for generated files using Squadron with source_gen?
If yes, could you provide an example of the correct configuration in build.yaml?
Thank you for your assistance!
